baseURL = "/"
languageCode = "en-US"
title = "fohte.net"
author = "Hayato Kawai"
theme = "cocoa-eh"
googleanalytics = "UA-49994513-2"

[params]
highlightjs = true
twitter = "fohte"
github = "fohte"
email = "fohte.hk@gmail.com"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
posts_navigation = true
latestpostcount = 5
disablefancyfonts = true
enlarged = true
logofile = "img/icon.png"
faviconfile = "img/icon.png"

[blackfriday]
extensions = ["hardLineBreak"]
